version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure

  zipkin:
    image: openzipkin/zipkin
    restart: on-failure
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus
    restart: on-failure
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    restart: on-failure
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: opentelemetry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust # Allow connections without a password locally
    ports:
      - "5432:5432"
